#!/bin/bash

export PATH=/bin:/usr/bin:/usr/local/bin

if [[ -z `which convert` || -z `which gs` ]]; then
    echo "ImageMagick and Ghostscript are required!"
    exit 1
fi

if [[ -z $1 || -z $2 ]]; then
    echo "Usage: $0 <icon> <version> (<branch>) (<repo>)"
    exit 1
fi

base_path=$1
echo "burning file ${base_path}"

version=$2
branch=$3
repo=$4

line_count=1
caption="${version}"

if [[ $branch ]]; then
	caption="${branch}\n${caption}"
	line_count=$(($line_count + 1))
fi

if [[ $repo ]]; then
	caption="${repo}\n${caption}"
	line_count=$(($line_count + 1))
fi

echo "burning caption ${caption}"

if [[ `uname -s` == 'Darwin' ]]; then
    xcrun -sdk iphoneos pngcrush -revert-iphone-optimizations -q ${base_path} ${base_path}-out
    mv ${base_path}-out ${base_path}
fi

width=`identify -format %w ${base_path}`
height=`identify -format %h ${base_path}`
point_size=$(((13 * $width) / 100))
band_height=$(($line_count * $point_size + ($height / 10)))
band_position=$(($height - $band_height))
text_position=$(($band_position - 3))

echo "image dimensions ${width}x${height} - band height ${band_height} @ ${band_position} - point size ${point_size}"

convert ${base_path} -blur 10x8 /tmp/blurred.png
convert /tmp/blurred.png -gamma 0 -fill white -draw "rectangle 0,$band_position,$width,$height" /tmp/mask.png
convert -size ${width}x${band_height} xc:none -fill 'rgba(0,0,0,0.2)' -draw "rectangle 0,0,$width,$band_height" /tmp/labels-base.png
convert -background none -size ${width}x${band_height} -pointsize $point_size -fill white -gravity center -gravity South caption:"$caption" /tmp/labels.png

convert ${base_path} /tmp/blurred.png /tmp/mask.png -composite /tmp/temp.png

rm /tmp/blurred.png
rm /tmp/mask.png

target_path=${base_path}
convert /tmp/temp.png /tmp/labels-base.png -geometry +0+$band_position -composite /tmp/labels.png -geometry +0+$text_position -geometry +${w}-${h} -composite "${target_path}"

rm /tmp/temp.png
rm /tmp/labels-base.png
rm /tmp/labels.png

echo "burned ${target_path}"
